services:
  ladesa-ro-auth-db:
    image: bitnami/postgresql:15
    container_name: ladesa-ro-auth-db
    volumes:
      - "ladesa-ro-auth-db-data:/bitnami/postgresql"
      - "./volumes/db/scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    env_file:
      - .kc-db.env
    networks:
      ladesa-net:
    ports:
      - 127.128.5.11:5432:5432

  ladesa-ro-auth:
    build:
      context: ../../
      args:
        - KEYCLOAK_EXTRA_ARGS=-Dkeycloak.profile.feature.scripts=enabled
    entrypoint: /opt/keycloak/bin/kc.sh
    command: start-dev --import-realm
    container_name: ladesa-ro-auth
    volumes:
      - ./data/import:/opt/keycloak/data/import/
    env_file:
      - .kc.env
    depends_on:
      - ladesa-ro-auth-db
    networks:
      ladesa-net:
    ports:
      - 127.128.5.10:8080:8080

networks:
  ladesa-net:
    external: true

volumes:
  ladesa-ro-auth-db-data:
