services:
  sisgea-servc-idp-db:
    image: bitnami/postgresql:15
    container_name: sisgea-servc-idp-db
    volumes:
      - "sisgea-servc-idp-db-data:/bitnami/postgresql"
      - "./volumes/db/scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    env_file:
      - .kc-db.env
    networks:
      sisgea-net:
    ports:
      - 127.128.5.11:5432:5432

  sisgea-servc-idp:
    build:
      context: ../docker/sso/image
      args:
        - KEYCLOAK_EXTRA_ARGS=-Dkeycloak.profile.feature.scripts=enabled
    entrypoint: /opt/keycloak/bin/kc.sh
    command: start-dev --import-realm
    container_name: sisgea-servc-idp
    env_file:
      - .kc.env
    depends_on:
      - sisgea-servc-idp-db
    networks:
      sisgea-net:
    ports:
      - 127.128.5.10:8080:8080

networks:
  sisgea-net:
    external: true

volumes:
  sisgea-servc-idp-db-data:
